name: task_manager_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  internet_connection_checker: ^1.0.0+1
  injectable: ^1.5.3
  formz: ^0.6.0
  flutter_screenutil: ^5.8.4
  shared_preferences: ^2.2.0
  dio: ^5.3.0
  logger: ^2.0.1
  intl: ^0.18.0
  google_fonts: ^5.1.0
  google_maps_flutter: ^2.4.0
  location: ^5.0.1
  font_awesome_flutter: ^10.5.0
  pin_code_fields: ^8.0.1
  flutter_svg: ^2.0.7
  easy_localization: ^3.0.2
  go_router: ^10.0.0
  dotted_border: ^2.0.0+2
  bloc: ^8.1.2
  lottie: ^2.5.0
  flutter_bloc: ^8.1.3
  get_it: ^7.2.0
  image_picker: ^1.0.2
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  dotted_decoration: ^2.0.0
  equatable: ^2.0.5
  pull_to_refresh: ^2.0.0
  geocoding: ^2.1.0
  fluttertoast: ^8.2.2
  url_launcher: ^6.1.12
  intl_phone_field: ^3.2.0
  cached_network_image: ^3.2.3
  palette_generator: ^0.3.3+2
  csc_picker: ^0.2.7
  http: ^1.1.0
  extended_sliver: ^2.1.3
  flutter_html: ^3.0.0-beta.2
  readmore: ^2.2.0
  getwidget: ^4.0.0
  firebase_core: ^2.16.0
  firebase_messaging: ^14.6.8
  flutter_local_notifications: ^15.1.1
  shimmer: ^3.0.0
  day_night_time_picker: ^1.3.0+1
  sqflite: ^2.3.2
  connectivity: ^3.0.6
  sqflite_common_ffi: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  injectable_generator: ^1.5.4
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  #notiice dev dependency!!!!!!!!!
  flutter_launcher_icons: "^0.9.2"
  pretty_dio_logger: ^1.3.1

# flutter_icons:
#   android: true
#   ios: true
#   remove_alpha_ios: true
#   image_path: "assets/icons/appicon.png"
#   #flutter pub run flutter_launcher_icons:main


flutter_gen:
  output: lib/core/presentation/resources/
  line_length: 80 # Optional (default: 80)

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/temp/
    - assets/lang/
    - assets/json_animations/
    - assets/google_maps_styles/
    - assets/fonts/

  fonts:
    - family: SST
      fonts:
        - asset: assets/fonts/SST-Arabic-Light-1.ttf
          weight: 200
        - asset: assets/fonts/SST-Arabic-Roman-1.ttf
          weight: 300
        - asset: assets/fonts/SST-Arabic-Roman-1.ttf
          weight: 400
        - asset: assets/fonts/SST-arabic-medium.ttf
          weight: 500
        - asset: assets/fonts/SST-arabic-medium.ttf
          weight: 600
        - asset: assets/fonts/SST-arabic-bold.ttf
          weight: 700
        - asset: assets/fonts/SST-arabic-bold.ttf
          weight: 800
        - asset: assets/fonts/SST-arabic-bold.ttf
          weight: 900
